CREATE DATABASE IF NOT EXISTS user_management DEFAULT CHARACTER SET utf8mb4;
USE user_management;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_time DATETIME NOT NULL,
  updated_time DATETIME
);
